export enum DomainErrorCode {
  ID_REQUIRED = 'ID_REQUIRED',
  ID_INVALID_FORMAT = 'ID_INVALID_FORMAT',

  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_INVALID_FORMAT = 'USER_EMAIL_INVALID_FORMAT',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_ALREADY_SUSPENDED = 'USER_ALREADY_SUSPENDED',
  USER_NOT_SUSPENDED = 'USER_NOT_SUSPENDED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
