export enum DomainErrorCode {
  ID_REQUIRED = 'ID_REQUIRED',
  ID_INVALID_FORMAT = 'ID_INVALID_FORMAT',

  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_INVALID_FORMAT = 'USER_EMAIL_INVALID_FORMAT',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_ALREADY_SUSPENDED = 'USER_ALREADY_SUSPENDED',
  USER_NOT_SUSPENDED = 'USER_NOT_SUSPENDED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  HASH_REQUIRED = 'HASH_REQUIRED',
  HASH_EXCEEDS_MAX_LENGTH = 'HASH_EXCEEDS_MAX_LENGTH',
  HASH_INVALID_FORMAT = 'HASH_INVALID_FORMAT',

  AUTH_IDENTITY_NOT_FOUND = 'AUTH_IDENTITY_NOT_FOUND',

  INVALID_PROVIDER = 'INVALID_PROVIDER',

  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS',
  PROFILE_FIRST_NAME_REQUIRED = 'PROFILE_FIRST_NAME_REQUIRED',
  PROFILE_LAST_NAME_REQUIRED = 'PROFILE_LAST_NAME_REQUIRED',
  PROFILE_BIRTH_DATE_REQUIRED = 'PROFILE_BIRTH_DATE_REQUIRED',
  PROFILE_BIRTH_DATE_INVALID = 'PROFILE_BIRTH_DATE_INVALID',
  PROFILE_PICTURE_INVALID_FORMAT = 'PROFILE_PICTURE_INVALID_FORMAT',
  PROFILE_PICTURE_TOO_LARGE = 'PROFILE_PICTURE_TOO_LARGE',

  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_TITLE_REQUIRED = 'SERVICE_TITLE_REQUIRED',
  SERVICE_DESCRIPTION_REQUIRED = 'SERVICE_DESCRIPTION_REQUIRED',
  SERVICE_PRICE_INVALID = 'SERVICE_PRICE_INVALID',
  SERVICE_UNAUTHORIZED = 'SERVICE_UNAUTHORIZED',
}
