export enum DomainErrorCode {
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_ALREADY_SUSPENDED = 'USER_ALREADY_SUSPENDED',
  USER_NOT_SUSPENDED = 'USER_NOT_SUSPENDED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_HAS_ROLE = 'USER_ALREADY_HAS_ROLE',

  AUTH_IDENTITY_NOT_FOUND = 'AUTH_IDENTITY_NOT_FOUND',

  INVALID_PROVIDER = 'INVALID_PROVIDER',
  PROVIDER_CONFLICT = 'PROVIDER_CONFLICT',

  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS',

  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_UNAUTHORIZED = 'SERVICE_UNAUTHORIZED',
  SERVICE_ALREADY_APPROVED = 'SERVICE_ALREADY_APPROVED',

  SERVICE_REQUEST_NOT_FOUND = 'SERVICE_REQUEST_NOT_FOUND',
  SERVICE_REQUEST_UNAUTHORIZED = 'SERVICE_REQUEST_UNAUTHORIZED',
  SERVICE_REQUEST_INVALID_TRANSITION = 'SERVICE_REQUEST_INVALID_TRANSITION',
  SERVICE_REQUEST_ALREADY_EXISTS = 'SERVICE_REQUEST_ALREADY_EXISTS',

  RATING_ALREADY_EXISTS = 'RATING_ALREADY_EXISTS',
  RATING_NOT_ALLOWED = 'RATING_NOT_ALLOWED',
}
